#!/usr/bin/env python
# coding: utf-8

# In[3]:


# 0.1 Install necessary dependencies
get_ipython().system('pip install requests')


# In[1]:


# 0.2 Import required libraries
import pandas as pd
import numpy as np
import time
import os
import json
import re
import docx
import glob
import requests


# In[3]:


# 0.3 Set path variables
CSV_path = 'Cases per paper.csv'
publications_dir = 'preprocess_outputs'
extraction_dir = 'LLM_extracted_IPD'

pilot_path = os.path.join(publications_dir, "pilot_set.json")
development_path = os.path.join(publications_dir, "development_set.json")
validation_path = os.path.join(publications_dir, "validation_set.json")


# In[5]:


# 0.4 Load the splited datasets from JSON files
with open(pilot_path, "r", encoding="utf-8") as f:
    pilot_data = json.load(f)
    
with open(development_path, "r", encoding="utf-8") as f:
    development_data = json.load(f)
    
with open(validation_path, "r", encoding="utf-8") as f:
    validation_data = json.load(f)


# In[7]:


# 0.5 Load the cases-per-study CSV file and standardize the study name
cases_df = pd.read_csv(CSV_path)
cases_df["Study Name"] = cases_df["0"].astype(str)


# In[9]:


# 1.1 Initialize the chat completion of OpenRouter
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
api_key = os.getenv("OPENROUTER_API_KEY")


# In[11]:


# 1.2 Set the prompt for code testing
prompt_files = sorted(glob.glob("32 Prompts/*.docx"))
prompts = {}
for pf in prompt_files:
    doc = docx.Document(pf)
    text = "\n".join([p.text for p in doc.paragraphs if p.text.strip()])
    prompts[os.path.basename(pf).split(".")[0]] = text
print(prompts.keys())


# In[13]:


# 1.3 Set the model to be tested
model = "meta-llama/llama-4-scout"


# In[15]:


# 2.1 Define a function to call the OpenRouter API
def call_openrouter(model, prompt, text):
    """
    Call the OpenRouter API to obtain model-generated responses.
    Parameters:
        model (str): The name of the model to use.
        prompt (str): The system prompt to define the model's behavior or role.
        text (str): The user's input text, which the model will respond to.
    Returns:
        str: The text content generated by the model.
    """
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",              ### Request body is JSON
    }

    payload = {
        "model": model,
        "temperature": 0,                                ### Set temperature to 0 for reproducability
        "messages": [
            {"role": "system", "content": "Only output JSON data and Do NOT include any text, explanation, or notes." + prompt},
            {"role": "user", "content": text}
        ]
    }
    
    response = requests.post(OPENROUTER_URL, headers=headers, json=payload)
    response.raise_for_status()
    data = response.json()                               ### Parse returned JSON
    return data["choices"][0]["message"]["content"]


# In[17]:


# 2.1 Define a function to extract and stucture IPD from single case reports 
def extract_case_report(model, prompt, study, text):
    """
    Extract IPD from a single case report.
    Parameters:
        model: The LLM instance used.
        prompt: The prompt text guiding extraction.
        study: Identifier of the study.
        text: The full text content of the single case report.
    Returns:
        A list containing the study name, extraction duration, and extracted patient features.
    """
    start_time = time.time()                                                                            ### Record start/end time for measuring duration

    output_text = call_openrouter(model, prompt, text)
    
    end_time = time.time()
    duration = end_time - start_time

    output_text = "".join(output_text)
    
    match = re.search(r"\[(.*?)\]", output_text, re.DOTALL)
    if match:
        output_json = match.group(1).strip()
    else:
        match = re.search(r"\{(.*?)\}", output_text, re.DOTALL)
        output_json = "{" + match.group(1).strip() + "}"

    output_json = output_json.replace("'", '"')
    data = json.loads("[" + output_json + "]")                                                                 ### Parse the JSON string to Python data structures                   
    IPD = data[0]
        
    Female = IPD.get("Female", None)
    Age = IPD.get("Age", None)
    SpeechDys = IPD.get("SpeechDys", None)
    Seizures = IPD.get("Seizures", None)
    MvmtDis = IPD.get("MvmtDis", None)
    Obtunded = IPD.get("Obtunded", None)
    BrainstemDys = IPD.get("BrainstemDys", None)
    BehCogImp = IPD.get("BehCogImp", None)
    ITU = IPD.get("ITU", None)
    WorstMRSAcute = IPD.get("WorstMRSAcute", None)
    EEGSlow = IPD.get("EEGSlow", None)
    EEGDeltaBrush = IPD.get("EEGDeltaBrush", None)
    EEGEpileptiform = IPD.get("EEGEpileptiform", None)
    CSFPleo = IPD.get("CSFPleo", None)
    CSFWBCQuant = IPD.get("CSFWBCQuant", None)
    AbnMRIBrain = IPD.get("ITU", None)
    Tumour = IPD.get("Tumour", None)
    DaysToIT = IPD.get("DaysToIT", None)
    ITWithin30Days = IPD.get("ITWithin30Days", None)
    IT1stLineCombo = IPD.get("IT1stLineCombo", None)
    IT2ndLineRTX = IPD.get("IT2ndLineRTX", None)
    IT2ndLineCYC = IPD.get("IT2ndLineCYC", None)
    IT2ndLineBort = IPD.get("IT2ndLineBort", None)
    IT2ndLineToc = IPD.get("IT2ndLineToc", None)
    ITMaintenanceMMF = IPD.get("ITMaintenanceMMF", None)
    ITMaintenanceAZA = IPD.get("ITMaintenanceAZA", None)
    ITMaintenanceMTX = IPD.get("ITMaintenanceMTX", None)
    IT6mSteroid = IPD.get("IT6mSteroid", None)
    IT6mIVIG = IPD.get("IT6mIVIG", None)
    MonthsToFU = IPD.get("MonthsToFU", None)
    FinalMRS = IPD.get("FinalMRS", None)
    Relapse = IPD.get("Relapse", None)
    
    output = [
        study, duration,
        Female, Age, SpeechDys, Seizures, MvmtDis, Obtunded, BrainstemDys, BehCogImp, ITU, WorstMRSAcute,
        EEGSlow, EEGDeltaBrush, EEGEpileptiform, CSFPleo, CSFWBCQuant, AbnMRIBrain, Tumour, DaysToIT, ITWithin30Days, IT1stLineCombo,
        IT2ndLineRTX, IT2ndLineCYC, IT2ndLineBort, IT2ndLineToc, ITMaintenanceMMF, ITMaintenanceAZA, ITMaintenanceMTX, IT6mSteroid, IT6mIVIG, MonthsToFU,
        FinalMRS, Relapse
    ]
    
    return output


# In[19]:


# 2.2 Define a function to extract and stucture multiple entries of IPD from case series 
def extract_case_series(model, prompt, study, text):
    """
    Extract IPD from a case series.
    Parameters:
        model: The LLM instance used.
        prompt: The prompt text guiding extraction.
        study: Identifier of the study.
        text: The full text content of the single case report.
    Returns:
        A list of lists, each inner list representing extracted features for a single patient in the series.
    """
    start_time = time.time()

    output_text = call_openrouter(model, prompt, text)
       
    end_time = time.time()
    duration = end_time - start_time

    output_text = "".join(output_text)
    
    all_matches = re.findall(r"\{(.*?)\}", output_text, re.DOTALL)
    data = [json.loads("{" + match.strip()+ "}") for match in all_matches]
    
    output = []                                                                     ### Define a list to contain lists of each series
    for IPD in data:                                                                ### Iterate over each patient's data in the series
        Female = IPD.get("Female", None)
        Age = IPD.get("Age", None)
        SpeechDys = IPD.get("SpeechDys", None)
        Seizures = IPD.get("Seizures", None)
        MvmtDis = IPD.get("MvmtDis", None)
        Obtunded = IPD.get("Obtunded", None)
        BrainstemDys = IPD.get("BrainstemDys", None)
        BehCogImp = IPD.get("BehCogImp", None)
        ITU = IPD.get("ITU", None)
        WorstMRSAcute = IPD.get("WorstMRSAcute", None)
        EEGSlow = IPD.get("EEGSlow", None)
        EEGDeltaBrush = IPD.get("EEGDeltaBrush", None)
        EEGEpileptiform = IPD.get("EEGEpileptiform", None)
        CSFPleo = IPD.get("CSFPleo", None)
        CSFWBCQuant = IPD.get("CSFWBCQuant", None)
        AbnMRIBrain = IPD.get("ITU", None)
        Tumour = IPD.get("Tumour", None)
        DaysToIT = IPD.get("DaysToIT", None)
        ITWithin30Days = IPD.get("ITWithin30Days", None)
        IT1stLineCombo = IPD.get("IT1stLineCombo", None)
        IT2ndLineRTX = IPD.get("IT2ndLineRTX", None)
        IT2ndLineCYC = IPD.get("IT2ndLineCYC", None)
        IT2ndLineBort = IPD.get("IT2ndLineBort", None)
        IT2ndLineToc = IPD.get("IT2ndLineToc", None)
        ITMaintenanceMMF = IPD.get("ITMaintenanceMMF", None)
        ITMaintenanceAZA = IPD.get("ITMaintenanceAZA", None)
        ITMaintenanceMTX = IPD.get("ITMaintenanceMTX", None)
        IT6mSteroid = IPD.get("IT6mSteroid", None)
        IT6mIVIG = IPD.get("IT6mIVIG", None)
        MonthsToFU = IPD.get("MonthsToFU", None)
        FinalMRS = IPD.get("FinalMRS", None)
        Relapse = IPD.get("Relapse", None)
    
        records = [
            study, duration,
            Female, Age, SpeechDys, Seizures, MvmtDis, Obtunded, BrainstemDys, BehCogImp, ITU, WorstMRSAcute,
            EEGSlow, EEGDeltaBrush, EEGEpileptiform, CSFPleo, CSFWBCQuant, AbnMRIBrain, Tumour, DaysToIT, ITWithin30Days, IT1stLineCombo,
            IT2ndLineRTX, IT2ndLineCYC, IT2ndLineBort, IT2ndLineToc, ITMaintenanceMMF, ITMaintenanceAZA, ITMaintenanceMTX, IT6mSteroid, IT6mIVIG, MonthsToFU,
            FinalMRS, Relapse
        ]
        output.append(records)
        
    return output


# In[21]:


# 2.3 Define a function to batch process a dataset of study and texts
def batch_feature_extraction(model, prompt, dataset):
    """
    Extract IPD either as single case reports or case series depending on the number of cases.
    Parameters:
        model: The LLM instance used.
        prompt: The prompt text guiding extraction.
        dataset: Dictionary mapping study identifiers to their full text content.
    Returns:
        A pandas DataFrame containing all extracted features for all studies/cases.
    """
    records = []
    for study, text in dataset.items():
        n_cases = cases_df.loc[cases_df["Study Name"] == study, "count"].values[0]          ### Look up number of cases for this study
        
        if n_cases == 1:
            records.append(extract_case_report(model, prompt, study, text))
        else:
            series_records = extract_case_series(model, prompt, study, text)
            records.extend(series_records)
            
        time.sleep(5)                                                                       ### Pause 5 seconds between each request to avoid rate limiting.

    df = pd.DataFrame(records, columns=["Study", "Duration", 
                                        "Female", "Age", "SpeechDys", "Seizures", "MvmtDis", "Obtunded", "BrainstemDys", "BehCogImp", "ITU", "WorstMRSAcute",
                                        "EEGSlow", "EEGDeltaBrush", "EEGEpileptiform", "CSFPleo", "CSFWBCQuant", "AbnMRIBrain", "Tumour", "DaysToIT", "ITWithin30Days", "IT1stLineCombo",
                                        "IT2ndLineRTX", "IT2ndLineCYC", "IT2ndLineBort", "IT2ndLineToc", "ITMaintenanceMMF", "ITMaintenanceAZA", "ITMaintenanceMTX", "IT6mSteroid", "IT6mIVIG", "MonthsToFU",
                                        "FinalMRS", "Relapse"
                                       ])
    return df                                                                               ### Convert all records into a DataFrame


# In[23]:


# 3.1 Run batch extraction on the pilot dataset
results_pilot = {}
for prompt_id, prompt in prompts.items():
    print(f"Running extraction with prompt {prompt_id} ...")
    records = []

    pilot_output = batch_feature_extraction(model, prompt, pilot_data)
    pilot_output_path = os.path.join(extraction_dir, f'pilot_output_{prompt_id}.csv')
    pilot_output.to_csv(pilot_output_path, index=False) 
    
    results_pilot[prompt_id] = pilot_output


# In[21]:


# 3.2 Run batch extraction on the development dataset
results_development = {}
for prompt_id, prompt in prompts.items():
    print(f"Running extraction with prompt {prompt_id} ...")
    records = []

    development_output = batch_feature_extraction(model, prompt, development_data)
    development_output_path = os.path.join(extraction_dir, f'development_output_{prompt_id}.csv')
    development_output.to_csv(development_output_path, index=False) 
    
    results_development[prompt_id] = development_output

